"""migration010

Revision ID: 16261ed2862b
Revises: 6d0ee1862010
Create Date: 2026-05-08 11:02:02.848587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16261ed2862b'
down_revision: Union[str, Sequence[str], None] = '6d0ee1862010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('webhook_logs', 'topic',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint('uq_webhook_logs_topic_resource_id', 'webhook_logs', ['topic', 'resource_id', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_webhook_logs_topic_resource_id', 'webhook_logs', type_='unique')
    op.alter_column('webhook_logs', 'topic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('subscriptions', 'updated_at')
    # ### end Alembic commands ###
