"""migration009

Revision ID: 6d0ee1862010
Revises: a5a9314ba01b
Create Date: 2026-04-17 10:12:37.049514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0ee1862010'
down_revision: Union[str, Sequence[str], None] = 'a5a9314ba01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'max_funcionarios')
    op.drop_column('companies', 'max_gestores')
    op.drop_index(op.f('ix_subscription_plans_mp_plan_id'), table_name='subscription_plans')
    op.drop_column('subscription_plans', 'mp_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('mp_plan_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_subscription_plans_mp_plan_id'), 'subscription_plans', ['mp_plan_id'], unique=False)
    op.add_column('companies', sa.Column('max_gestores', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('max_funcionarios', sa.SMALLINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
