"""add subscriptions and webhook tables

Revision ID: 7eabb9230fae
Revises: ce130ae84ac3
Create Date: 2026-03-09 15:21:45.751256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eabb9230fae'
down_revision: Union[str, Sequence[str], None] = 'ce130ae84ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('type', sa.Enum('corporative', 'individual', name='plan_type'), nullable=False),
    sa.Column('price_in_cents', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Enum('monthly', 'quarterly', 'semiannual', 'annual', name='plan_period'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mp_plan_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_mp_plan_id'), 'subscription_plans', ['mp_plan_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'success', 'ignored', 'error', name='webhook_status'), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_resource_id'), 'webhook_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_topic'), 'webhook_logs', ['topic'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('trialing', 'active', 'overdue', 'unpaid', 'canceled', 'incomplete', name='subscription_status'), nullable=False),
    sa.Column('initial_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_quantity', sa.Integer(), nullable=False),
    sa.Column('mp_subscription_id', sa.String(), nullable=True),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_mp_subscription_id'), 'subscriptions', ['mp_subscription_id'], unique=False)

    # --- clients ---
    op.add_column('clients', sa.Column('manager_id', sa.BigInteger(), nullable=True))
    # cpf: adiciona nullable, preenche existentes, torna NOT NULL
    op.add_column('clients', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.execute("UPDATE clients SET cpf = lpad(id::text, 11, '0') WHERE cpf IS NULL")
    op.alter_column('clients', 'cpf', nullable=False)
    # telefone: mesmo padrão
    op.add_column('clients', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.execute("UPDATE clients SET telefone = concat('000000', id::text) WHERE telefone IS NULL")
    op.alter_column('clients', 'telefone', nullable=False)
    op.create_index(op.f('ix_clients_telefone'), 'clients', ['telefone'], unique=False)
    op.create_unique_constraint(None, 'clients', ['cpf'])
    op.create_foreign_key(None, 'clients', 'managers', ['manager_id'], ['id'])

    # --- companies ---
    op.add_column('companies', sa.Column('nome_fantasia', sa.String(length=255), nullable=True))
    op.execute("UPDATE companies SET nome_fantasia = '' WHERE nome_fantasia IS NULL")
    op.alter_column('companies', 'nome_fantasia', nullable=False)

    op.add_column('companies', sa.Column('razao_social', sa.String(length=255), nullable=True))
    op.execute("UPDATE companies SET razao_social = '' WHERE razao_social IS NULL")
    op.alter_column('companies', 'razao_social', nullable=False)

    op.add_column('companies', sa.Column('email', sa.String(length=100), nullable=True))
    op.execute("UPDATE companies SET email = concat('empresa_legada_', id::text, '@placeholder.com') WHERE email IS NULL")
    op.alter_column('companies', 'email', nullable=False)

    op.add_column('companies', sa.Column('cnpj', sa.String(length=18), nullable=True))
    op.execute("UPDATE companies SET cnpj = concat('00000000000', id::text) WHERE cnpj IS NULL")
    op.alter_column('companies', 'cnpj', nullable=False)

    op.add_column('companies', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.execute("UPDATE companies SET telefone = '00000000000' WHERE telefone IS NULL")
    op.alter_column('companies', 'telefone', nullable=False)

    op.add_column('companies', sa.Column('login', sa.String(), nullable=True))
    op.execute("UPDATE companies SET login = concat('empresa_legada_', id::text) WHERE login IS NULL")
    op.alter_column('companies', 'login', nullable=False)

    op.add_column('companies', sa.Column('senha_hash', sa.String(length=255), nullable=True))
    op.execute("UPDATE companies SET senha_hash = 'PLACEHOLDER_RESET_REQUIRED' WHERE senha_hash IS NULL")
    op.alter_column('companies', 'senha_hash', nullable=False)

    op.create_index(op.f('ix_companies_telefone'), 'companies', ['telefone'], unique=False)
    op.create_unique_constraint(None, 'companies', ['email'])
    op.create_unique_constraint(None, 'companies', ['cnpj'])
    op.create_unique_constraint(None, 'companies', ['login'])
    op.drop_column('companies', 'nome')

    # --- managers ---
    op.add_column('managers', sa.Column('nome', sa.String(length=100), nullable=True))
    op.execute("UPDATE managers SET nome = 'Gestor Legado' WHERE nome IS NULL")
    op.alter_column('managers', 'nome', nullable=False)

    op.add_column('managers', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.execute("UPDATE managers SET cpf = concat('0000000', id::text) WHERE cpf IS NULL")
    op.alter_column('managers', 'cpf', nullable=False)

    op.add_column('managers', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.execute("UPDATE managers SET telefone = '00000000000' WHERE telefone IS NULL")
    op.alter_column('managers', 'telefone', nullable=False)

    op.add_column('managers', sa.Column('email', sa.String(length=100), nullable=True))
    op.execute("UPDATE managers SET email = concat('gestor_legado_', id::text, '@placeholder.com') WHERE email IS NULL")
    op.alter_column('managers', 'email', nullable=False)

    op.create_index(op.f('ix_managers_telefone'), 'managers', ['telefone'], unique=False)
    op.create_unique_constraint(None, 'managers', ['cpf'])
    op.create_unique_constraint(None, 'managers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managers', type_='unique')
    op.drop_constraint(None, 'managers', type_='unique')
    op.drop_index(op.f('ix_managers_telefone'), table_name='managers')
    op.drop_column('managers', 'email')
    op.drop_column('managers', 'telefone')
    op.drop_column('managers', 'cpf')
    op.drop_column('managers', 'nome')
    op.add_column('companies', sa.Column('nome', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_telefone'), table_name='companies')
    op.drop_column('companies', 'senha_hash')
    op.drop_column('companies', 'login')
    op.drop_column('companies', 'telefone')
    op.drop_column('companies', 'cnpj')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'razao_social')
    op.drop_column('companies', 'nome_fantasia')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_telefone'), table_name='clients')
    op.drop_column('clients', 'telefone')
    op.drop_column('clients', 'cpf')
    op.drop_column('clients', 'manager_id')
    op.drop_index(op.f('ix_subscriptions_mp_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_webhook_logs_topic'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_resource_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_subscription_plans_mp_plan_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
