"""migration008

Revision ID: a5a9314ba01b
Revises: 8245bccc1d95
Create Date: 2026-04-02 11:48:52.375338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a9314ba01b'
down_revision: Union[str, Sequence[str], None] = '8245bccc1d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'nome_completo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    op.alter_column('clients', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.drop_constraint(op.f('companies_login_key'), 'companies', type_='unique')
    op.drop_column('companies', 'login')
    op.drop_constraint(op.f('managers_login_key'), 'managers', type_='unique')
    op.drop_column('managers', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('login', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('managers_login_key'), 'managers', ['login'], postgresql_nulls_not_distinct=False)
    op.add_column('companies', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('companies_login_key'), 'companies', ['login'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    op.alter_column('clients', 'nome_completo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
