"""migration004

Revision ID: c92a1936dc0e
Revises: d2136fee261b
Create Date: 2026-03-16 09:52:41.406100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92a1936dc0e'
down_revision: Union[str, Sequence[str], None] = 'd2136fee261b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('max_managers_purchased', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('max_employees_purchased', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'max_employees_purchased')
    op.drop_column('subscriptions', 'max_managers_purchased')
    # ### end Alembic commands ###
