"""migration003

Revision ID: d2136fee261b
Revises: 7eabb9230fae
Create Date: 2026-03-11 11:07:23.537622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2136fee261b'
down_revision: Union[str, Sequence[str], None] = '7eabb9230fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subscriptions_manager_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('manager_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('subscriptions_manager_id_fkey'), 'subscriptions', 'managers', ['manager_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
